name: ThotPatrol
version: 1.3.5
author: frep
main: me.frep.thotpatrol.ThotPatrol
load: STARTUP
depend: [ProtocolLib]

commands:
  alerts:
    description: Toggles off and on alerts
  autoban:
    description: Stops autobanning
  thotpatrol:
    description: Thot Patrol root command
    aliases: [anticheat]
  getlog:
    description: Get a player's log!
  JDay:
    description: Judgement Day

permissions:
  thotpatrol.staff:
    description: Gives access to staff
    default: op
  thotpatrol.admin:
    description: Gives access to admin
    default: op
  thotpatrol.log:
    description: Gives access to /getlog
    default: op
  thotpatrol.bypass:
    default: false
    description: Bypass node.